/* funciones que sirven para ejecutar cierta parte del código */
//PARA LOS PROYECTOS

export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const VALIDAR_FORMULARIO_PROYECTO = 'VALIDAR_FORMULARIO_PROYECTO';
export const SELECCIONAR_PROYECTO_ACTUAL = "SELECCIONAR_PROYECTO_ACTUAL";
export const LISTA_PROYECTO = 'LISTA_PROYECTO';
export const REGISTRAR_PROYECTO = 'REGISTRAR_PROYECTO';
export const MODIFICAR_PROYECTO = 'MODIFICAR_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

//PARA LAS TAREAS

export const FORMULARIO_TAREA = 'FORMULARIO_TAREA';
export const VALIDAR_FORMULARIO_TAREAS = 'VALIDAR_FORMULARIO_TAREAS';
export const LISTA_TAREAS_POR_PROYECTO = 'LISTA_TAREAS_POR_PROYECTO';
export const REGISTRAR_TAREA = 'REGISTRAR_TAREA';
export const SELECCIONAR_TAREA_ACTUAL = "SELECCIONAR_TAREA_ACTUAL";
export const MODIFICAR_TAREA = 'MODIFICAR_TAREA';
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";

// PARA LA AUTENTICACIÓN DE USUARIOS
export const REGISTRO_EXITOSO = 'REGISTRO_EXISTOSO';
export const REGISTRO_ERRONEO = 'REGISTRO_ERRONEO';
export const OBTENER_INFO_USUARIO = 'OBTENER_INFO_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERRONEO = 'LOGIN_ERRONEO';
export const CERRAR_SESION = 'CERRAR_SESION';

//BORRAR MENSAJES DE ALERTA
export const BORRAR_MENSAJES = 'BORRAR_MENSAJES';